// This file is auto-generated by the Blippar 3ds Max Exporter
// 2017-03-13.10:58:25
//
// WARNING: This file contains a complete blipp of your exported scene from 3ds Max.
// Please do not modify this file directly, copy and paste the code stub into your own javascript source.
//
// This file may be overwritten by future exports, so modifications will be lost.
//

var blipp = require('blippar').blipp;
var scene = blipp.addScene('default');

scene.addMaterial('Default')
     .setType('matt');

// RenderBin: 50
var root = scene.addTransform('scene_main');

var Link = root.addMesh('Link.b3m')
               .setName('Link')
               .setType('solid')
               .setColor([0.423529, 0.0313726, 0.533333])
               .setMaterial('Default');


// RenderBin: 2000
scene.onShow = function() {
}


