// This file is auto-generated by the Blippar 3ds Max Exporter
// 2017-02-20.09:48:28
//
// WARNING: This file contains a complete blipp of your exported scene from 3ds Max.
// Please do not modify this file directly, copy and paste the code stub into your own javascript source.
//
// This file may be overwritten by future exports, so modifications will be lost.
//

var blipp = require('blippar').blipp;
var scene = blipp.addScene('default');

scene.addMaterial('Default')
     .setType('matt');

// RenderBin: 50
var root = scene.addTransform('scene_new');

var Box001 = root.addMesh('Box001.b3m')
                 .setName('Box001')
                 .setType('solid')
                 .setTranslation(-3.940125, -5.635376, 0)
                 .setColor([0.341, 0.882, 0.561])
                 .setMaterial('Default');


// RenderBin: 2000
scene.onShow = function() {
}


