// This file is auto-generated by the Blippar 3ds Max Exporter
// 2017-03-07.12:26:15
//
// WARNING: This file contains a complete blipp of your exported scene from 3ds Max.
// Please do not modify this file directly, copy and paste the code stub into your own javascript source.
//
// This file may be overwritten by future exports, so modifications will be lost.
//

var blipp = require('blippar').blipp;
var scene = blipp.addScene('default');

scene.addMaterial('Default')
     .setType('matt');

// RenderBin: 50
var root = scene.addTransform('scene_ponty');

var Pointer = root.addMesh('Pointer.b3m')
                  .setName('Pointer')
                  .setType('solid')
                  .setTranslation(-400, -100, 500)
                  .setColor([0.106, 0.694, 0.106])
                  .setMaterial('Default');
var Pointer_axis = Pointer.addMesh('internal.axis')
                          .setName('Pointer_axis')
                          .setType('aura')
                          .setTexture('internal.image.axis');
var Pointer_node = Pointer.addMesh('internal.axis')
                          .setName('Pointer_node')
                          .setType('aura')
                          .setColor([0.000, 0.000, 0.500])
                          .setTexture('internal.image.axis');


// RenderBin: 2000
scene.onShow = function() {
}


