// This file is auto-generated by the Blippar 3ds Max Exporter
// 2017-02-28.07:53:22
//
// WARNING: This file contains a complete blipp of your exported scene from 3ds Max.
// Please do not modify this file directly, copy and paste the code stub into your own javascript source.
//
// This file may be overwritten by future exports, so modifications will be lost.
//

var blipp = require('blippar').blipp;
var scene = blipp.addScene('default');

scene.addMaterial('Default')
     .setType('matt');

// RenderBin: 50
var root = scene.addTransform('scene_tester');

var Box001 = root.addMesh('Box001.b3m')
                 .setName('Box001')
                 .setType('solid')
                 .setTranslation(43.703239, 35.226414, 49.007751)
                 .setRotation(32.235046, 16.445822, 53.138741)
                 .setScale(1.29025, 1.29025, 1.29025)
                 .setColor([0.529, 0.024, 0.024])
                 .setMaterial('Default');
var Box001_axis = Box001.addMesh('internal.axis')
                        .setName('Box001_axis')
                        .setType('aura')
                        .setTexture('internal.image.axis')
                        .setScale(0.775043, 0.775044, 0.775043);
var Box001_node = Box001.addMesh('internal.axis')
                        .setName('Box001_node')
                        .setType('aura')
                        .setColor([0.000, 0.000, 0.500])
                        .setTexture('internal.image.axis')
                        .setScale(0.775043, 0.775044, 0.775043);


// RenderBin: 2000
scene.onShow = function() {
}


