// This file is auto-generated by the Blippar 3ds Max Exporter
// 2017-03-03.11:05:05
//
// WARNING: This file contains a complete blipp of your exported scene from 3ds Max.
// Please do not modify this file directly, copy and paste the code stub into your own javascript source.
//
// This file may be overwritten by future exports, so modifications will be lost.
//

var blipp = require('blippar').blipp;
var scene = blipp.addScene('default');

scene.addMaterial('Default')
     .setType('matt');

// RenderBin: 50
var root = scene.addTransform('scene_lookat');

var Pointer = root.addMesh('assetsPointer.b3m')
                  .setName('Pointer')
                  .setType('solid')
                  .setTranslation(-400, -100, 200)
                  .setColor([0.106, 0.694, 0.106])
                  .setMaterial('Default');

var Target = root.addMesh('assetsTarget.b3m')
                 .setName('Target')
                 .setType('solid')
                 .setTranslation(300, 200, 100)
                 .setScale(1.460811, 1.460811, 1.460811)
                 .setColor([0.529, 0.024, 0.024])
                 .setMaterial('Default');


// RenderBin: 2000
scene.onShow = function() {
}


