// This file is auto-generated by the Blippar 3ds Max Exporter
// 2017-02-13.14:59:35
//
// WARNING: This file contains a complete blipp of your exported scene from 3ds Max.
// Please do not modify this file directly, copy and paste the code stub into your own javascript source.
//
// This file may be overwritten by future exports, so modifications will be lost.
//

var blipp = require('blippar').blipp;
var scene = blipp.addScene('default');

scene.addMaterial('Default')
     .setType('matt');

// RenderBin: 50
var root = scene.addTransform('scene_test');

var Base = root.addMesh('Base.b3m')
               .setName('Base')
               .setType('solid')
               .setColor([0.529412, 0.0235294, 0.0235294])
               .setMaterial('Default');

var Rot = Base.addMesh('Rot.b3m')
              .setName('Rot')
              .setType('solid')
              .setTranslation(0, 0, 286.447693)
              .setRotation(37.108582, 14.862703, 30.570572)
              .setColor([0.031, 0.239, 0.541])
              .setMaterial('Default');

var Box001 = root.addMesh('Box001.b3m')
                 .setName('Box001')
                 .setType('solid')
                 .setTranslation(-200, -200, 0)
                 .setColor([0.024, 0.529, 0.227])
                 .setMaterial('Default');

var Box002 = root.addMesh('Box002.b3m')
                 .setName('Box002')
                 .setType('solid')
                 .setTranslation(-200, 200, 0)
                 .setColor([0.024, 0.529, 0.227])
                 .setMaterial('Default');

var Box003 = root.addMesh('Box003.b3m')
                 .setName('Box003')
                 .setType('solid')
                 .setTranslation(200, 200, 0)
                 .setColor([0.024, 0.529, 0.227])
                 .setMaterial('Default');

var Box004 = root.addMesh('Box004.b3m')
                 .setName('Box004')
                 .setType('solid')
                 .setTranslation(200, -200, 0)
                 .setColor([0.024, 0.529, 0.227])
                 .setMaterial('Default');


// RenderBin: 2000
scene.onShow = function() {
}


