// This file is auto-generated by the Blippar 3ds Max Exporter
// 2017-03-13.10:06:27
//
// WARNING: This file contains a complete blipp of your exported scene from 3ds Max.
// Please do not modify this file directly, copy and paste the code stub into your own javascript source.
//
// This file may be overwritten by future exports, so modifications will be lost.
//

var blipp = require('blippar').blipp;
var scene = blipp.addScene('default');

scene.addMaterial('Default')
  .setType('matt');

// RenderBin: 1
var Globe = scene.addMaterial('Globe')
  .setSelfLightIntensity(0.36)
  .setType('matt');

var Iris = scene.addMaterial('Iris')
  .setSelfLightIntensity(0.36)
  .setType('matt')
  .setDiffuseColor([0.152941, 0.784314, 0.878431]);

var Pupil = scene.addMaterial('Pupil')
  .setSelfLightIntensity(0.36)
  .setType('matt')
  .setDiffuseColor([0, 0, 0]);

var Lids = scene.addMaterial('Lids')
  .setSelfLightIntensity(0.36)
  .setType('matt')
  .setDiffuseColor([0.588235, 0.313726, 0.231373]);


// RenderBin: 50
var Eye = scene.addTransform('scene_main').setScale(10);

var Eye_Globe = Eye.addMesh('Eye_Globe.b3m')
  .setName('Eye_Globe')
  .setType('solid')
  .setTranslation(-0.588463, -0.82385, 0)
  .setMaterial('Globe');

var Eye_Iris = Eye_Globe.addMesh('Eye_Iris.b3m')
  .setName('Eye_Iris')
  .setType('solid')
  .setTranslation(0, 0, 7.611631)
  .setScale(0.763341, 0.763341, 0.763341)
  .setMaterial('Iris');

var Eye_Pupil = Eye_Iris.addMesh('Eye_Pupil.b3m')
  .setName('Eye_Pupil')
  .setType('solid')
  .setTranslation(0, -0, 15.337182)
  .setScale(0.468982, 0.468982, 0.468982)
  .setMaterial('Pupil');

var Eye_Lid_Bottom = Eye.addMesh('Eye_Lid_Bottom.b3m')
  .setName('Eye_Lid_Bottom')
  .setType('solid')
  .setTranslation(-0.588463, -0.82385, 0)
  .setRotation(140, 0, -0)
  .setMaterial('Lids');

var Eye_Lid_Top = Eye.addMesh('Eye_Lid_Top.b3m')
  .setName('Eye_Lid_Top')
  .setType('solid')
  .setTranslation(-0.588463, -0.82385, 0)
  .setRotation(-140, 0, -0)
  .setMaterial('Lids');


// RenderBin: 2000
scene.onShow = function () {}