// This file is auto-generated by the Blippar 3ds Max Exporter
// 2017-02-15.10:04:00
//
// WARNING: This file contains a complete blipp of your exported scene from 3ds Max.
// Please do not modify this file directly, copy and paste the code stub into your own javascript source.
//
// This file may be overwritten by future exports, so modifications will be lost.
//

var blipp = require('blippar').blipp;
var scene = blipp.addScene('default');

scene.addMaterial('Default')
     .setType('matt');

// RenderBin: 1
var _01___Default = scene.addMaterial('01___Default')
                         .setType('matt')
                         .setDiffuseColor([0.0705882, 1, 0]);

var _02___Default = scene.addMaterial('02___Default')
                         .setType('matt');

var _03___Default = scene.addMaterial('03___Default')
                         .setType('matt')
                         .setDiffuseColor([1, 0, 0]);


// RenderBin: 50
var root = scene.addTransform('scene_new');

var A = root.addMesh('A.b3m')
            .setName('A')
            .setType('solid')
            .setTranslation(-107.51593, 60.505707, 0)
            .setRotation(-0, 0, 30.623669)
            .setScale(1.5, 1.5, 1.5)
            .setColor([0.529, 0.024, 0.024])
            .setMaterial('Default');

var B = A.addMesh('B.b3m')
         .setName('B')
         .setType('solid')
         .setTranslation(7.800129, -55.813934, 111.116089)
         .setRotation(-9.149782, -8.524243, 19.407499)
         .setScale(0.6, 0.6, 0.6)
         .setColor([0.898, 0.604, 0.843])
         .setMaterial('Default');

var C = B.addMesh('C.b3m')
         .setName('C')
         .setType('solid')
         .setTranslation(-119.695862, -69.40358, 519.784485)
         .setRotation(56.154945, -2.368725, 48.837994)
         .setScale(1.2, 1.2, 1.2)
         .setMaterial('01___Default')
         .setAlpha(0.300);

var CB = A.addMesh('CB.b3m')
          .setName('CB')
          .setType('solid')
          .setTranslation(-91.732086, -70.376282, 417.769623)
          .setRotation(44.531879, 8.72314, 66.879982)
          .setScale(0.72, 0.72, 0.72)
          .setMaterial('02___Default')
          .setAlpha(0.300);

var Cabs = root.addMesh('Cabs.b3m')
               .setName('Cabs')
               .setType('solid')
               .setTranslation(-172.149307, -100.427887, 626.654419)
               .setRotation(36.388062, 28.922029, 91.391266)
               .setScale(1.08, 1.08, 1.08)
               .setMaterial('03___Default')
               .setAlpha(0.300);


// RenderBin: 2000
scene.onShow = function() {
}


